spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eclipse:
  subscription:
    skip-time-check: true

logging:
  level:
    com.shinhan.eclipse: DEBUG
    org.hibernate.SQL: DEBUG
